= Service Poller

Manage services and update their status continuously.

== Architecture
The application is split into two verticles; a http-server verticle and a database verticle. The two verticles communicate through the eventbus. The application uses HTTP to receive requests and response to said requests. All services status are updated every minuted by utilizing the `ScheduledExecutorService` in the http-server verticle. This is subject to change.

== Note
The structure of the application is inspired by https://vertx.tk/docs/guide-for-java-devs/ though with using Vertx 4 rather than 3.

== How to configure

Running the following command will configure the application with the necessary dependencies:
```
./gradlew clean assemble
```

== How to run locally

The application can be run locally with the following command:
```
./gradlew clean run
```

== How to test

The application can be tested using the following command:
```
./gradlew clean test
```


== TODO
- Make available SQL queries independent of logic code
- Use Vertx services instead of eventbus
- Refactor 'updateServices' to use RxJava fully
- Secure application
- Update CORS headers to reflect production environment
- Make interval for updating services configurable
- Use Docker to initialize db and server automatically
- Add tests to remaining functionality
